### ISSUE TITLE
classdefnotfound error

### ISSUE THREAD

**Issue by jeetdholakia** [strider2023/Radial-Menu-Widget-Android#2]
Im getting these strange errors on every option (v1,v2,semicircle) , please help me out

08-09 22:31:57.242: E/AndroidRuntime(10702): FATAL EXCEPTION: main
08-09 22:31:57.242: E/AndroidRuntime(10702): java.lang.NoClassDefFoundError: com.touchmenotapps.radialdemo.RadialMenuActivity
08-09 22:31:57.242: E/AndroidRuntime(10702):    at com.touchmenotapps.radialdemo.MainMenu$1.onItemClick(MainMenu.java:35)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at android.widget.AdapterView.performItemClick(AdapterView.java:298)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at android.widget.AbsListView.performItemClick(AbsListView.java:1280)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3071)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at android.widget.AbsListView$1.run(AbsListView.java:3972)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at android.os.Handler.handleCallback(Handler.java:615)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at android.os.Handler.dispatchMessage(Handler.java:92)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at android.os.Looper.loop(Looper.java:137)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at android.app.ActivityThread.main(ActivityThread.java:4895)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at java.lang.reflect.Method.invokeNative(Native Method)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at java.lang.reflect.Method.invoke(Method.java:511)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
08-09 22:31:57.242: E/AndroidRuntime(10702):    at dalvik.system.NativeStart.main(Native Method)

**Comment by jeetdholakia** [comment]
never mind , i have solved it , please remove all radial widget libraries in your project because , the all the required classes are present inside the source, hence a lash between same classes inside jar and source :)
