### ISSUE TITLE
removeAllMenuItems

### ISSUE THREAD

**Issue by ProjectFF** [strider2023/Radial-Menu-Widget-Android#6]
i want to remove all items on click on an item to set new Icons. 

09-22 15:50:59.375: E/AndroidRuntime(5100): FATAL EXCEPTION: main
09-22 15:50:59.375: E/AndroidRuntime(5100): java.lang.NullPointerException
09-22 15:50:59.375: E/AndroidRuntime(5100):     at com.touchmenotapps.widget.radialmenu.semicircularmenu.SemiCircularRadialMenu.onTouchEvent(SemiCircularRadialMenu.java:177)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.View.dispatchTouchEvent(View.java:7669)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2283)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1578)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.app.Activity.dispatchTouchEvent(Activity.java:2468)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2231)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.View.dispatchPointerEvent(View.java:7876)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3898)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3782)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5034)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5013)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5112)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.os.MessageQueue.nativePollOnce(Native Method)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.os.MessageQueue.next(MessageQueue.java:125)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.os.Looper.loop(Looper.java:124)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at android.app.ActivityThread.main(ActivityThread.java:5279)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at java.lang.reflect.Method.invokeNative(Native Method)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at java.lang.reflect.Method.invoke(Method.java:511)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
09-22 15:50:59.375: E/AndroidRuntime(5100):     at dalvik.system.NativeStart.main(Native Method)

before i add a new Item i call removeAllMenuItems in an setOnSemiCircularRadialMenuPressed
method.

public void createMenuItem(final String name){

```
    int drawable = getResources().getIdentifier("btn_"+name, "drawable", "com.projectff.main");
    currentItem = new SemiCircularRadialMenuItem(name, getResources().getDrawable(drawable), name);

    mMenu.addMenuItem(name, currentItem);
    currentItem.setOnSemiCircularRadialMenuPressed(new OnSemiCircularRadialMenuPressed() {
        @Override
        public void onMenuItemPressed() {
            renderer.setAction(name);
        }});
}
```

I want to dynamically add new Items to the menu when clicking on a parent menuitem.

**Comment by EpicJoker93** [comment]
Due to the nature of the menu, being a canvas drawing, I think you would need to redraw the menu in order to add items dynamically. Menu item adding is done before draw as far as i know. onDraw is when the items are all drawn, so it should work if you can manage to reDraw it.
